// 全站 antd 主题令牌（视觉唯一来源；页面级颜色常量见 components/ui.jsx）
export const FONT_FAMILY =
  '-apple-system, BlinkMacSystemFont, "SF Pro Text", "PingFang SC", "Segoe UI", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif'

export const THEME = {
  token: {
    colorPrimary: '#2563eb',
    colorInfo: '#2563eb',
    colorLink: '#2563eb',
    colorLinkHover: '#1d4ed8',
    colorSuccess: '#16a34a',
    colorError: '#dc2626',
    colorWarning: '#f59e0b',
    colorText: '#0f172a',
    colorTextSecondary: '#5b6b82',
    colorTextTertiary: '#94a3b8',
    colorTextQuaternary: '#cbd5e1',
    colorBorder: '#d5dbe5',
    colorBorderSecondary: '#e5e9f0',
    colorBgLayout: '#f3f5f9',
    colorBgContainer: '#ffffff',
    colorFillAlter: '#f8fafc',
    borderRadius: 8,
    borderRadiusSM: 6,
    fontSize: 13,
    fontFamily: FONT_FAMILY,
    controlHeight: 34,
    controlHeightSM: 28,
    boxShadow: '0 4px 16px rgba(15, 23, 42, 0.08)',
    boxShadowSecondary: '0 8px 24px rgba(15, 23, 42, 0.10)',
  },
  components: {
    Button: { primaryShadow: 'none', defaultShadow: 'none', dangerShadow: 'none', fontWeight: 500 },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#5b6b82',
      headerSplitColor: 'transparent',
      rowHoverBg: '#f8fafc',
      borderColor: '#eef1f5',
      cellPaddingBlockSM: 8,
      cellPaddingInlineSM: 12,
      cellFontSizeSM: 13,
      headerSortActiveBg: '#f1f5f9',
      headerSortHoverBg: '#f1f5f9',
      bodySortBg: 'transparent',
    },
    Segmented: {
      itemSelectedBg: '#0f172a',
      itemSelectedColor: '#ffffff',
      itemColor: '#5b6b82',
      itemHoverColor: '#0f172a',
      trackBg: '#eef1f5',
      trackPadding: 3,
    },
    Tabs: {
      titleFontSize: 13,
      horizontalMargin: '0',
      horizontalItemPadding: '12px 0',
      inkBarColor: '#0f172a',
      itemSelectedColor: '#0f172a',
      itemColor: '#5b6b82',
      itemHoverColor: '#0f172a',
    },
    Select: { optionSelectedBg: '#eff6ff' },
    Switch: { trackHeight: 20, trackMinWidth: 36, handleSize: 16 },
    Modal: { borderRadiusLG: 14 },
    Message: { contentBg: '#0f172a', colorText: '#ffffff' },
    Spin: { colorPrimary: '#0f172a' },
  },
}
